export const mockData = {
    movies: [
      {
        id: 1,
        title: "Avengers: Endgame",
        description: "The Avengers assemble once more to reverse the damage caused by Thanos.",
        genre: "Action",
        duration: 181,
        poster: "/placeholder.svg?height=300&width=200",
        hasActiveShows: true,
      },
      {
        id: 2,
        title: "The Lion King",
        description: "A young lion prince flees his kingdom after the murder of his father.",
        genre: "Animation",
        duration: 118,
        poster: "/placeholder.svg?height=300&width=200",
        hasActiveShows: false,
      },
      {
        id: 3,
        title: "Joker",
        description: "A failed comedian begins a slow descent into madness.",
        genre: "Drama",
        duration: 122,
        poster: "/placeholder.svg?height=300&width=200",
        hasActiveShows: true,
      },
    ],
  
    theaters: [
      {
        id: 1,
        name: "Cineplex Downtown",
        location: "123 Main St, Downtown",
        capacity: 200,
        status: "approved",
        registrationDate: "2024-01-15",
      },
      {
        id: 2,
        name: "MovieMax Plaza",
        location: "456 Oak Ave, Plaza District",
        capacity: 150,
        status: "pending",
        registrationDate: "2024-01-20",
      },
      {
        id: 3,
        name: "Star Cinema",
        location: "789 Pine St, Uptown",
        capacity: 300,
        status: "approved",
        registrationDate: "2024-01-10",
      },
    ],
  
    users: [
      {
        id: 1,
        name: "John Doe",
        email: "john.doe@email.com",
        phone: "+1-555-0123",
        registrationDate: "2024-01-15",
        status: "active",
        totalBookings: 15,
      },
      {
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@email.com",
        phone: "+1-555-0124",
        registrationDate: "2024-01-18",
        status: "blocked",
        totalBookings: 8,
      },
      {
        id: 3,
        name: "Mike Johnson",
        email: "mike.johnson@email.com",
        phone: "+1-555-0125",
        registrationDate: "2024-01-20",
        status: "active",
        totalBookings: 22,
      },
    ],
  
    bookings: [
      {
        id: 1,
        userId: 1,
        movieId: 1,
        theaterId: 1,
        date: "2024-01-25",
        time: "19:00",
        seats: 2,
        amount: 24.0,
      },
      {
        id: 2,
        userId: 2,
        movieId: 2,
        theaterId: 2,
        date: "2024-01-25",
        time: "21:00",
        seats: 4,
        amount: 48.0,
      },
      {
        id: 3,
        userId: 3,
        movieId: 1,
        theaterId: 1,
        date: "2024-01-26",
        time: "16:00",
        seats: 3,
        amount: 36.0,
      },
    ],
  
    dashboardStats: {
      totalTheaters: 3,
      totalMovies: 3,
      totalUsers: 3,
      totalBookings: 150,
      todayRevenue: 2450.0,
      occupancyRate: 78,
    },
  }
  